### ISSUE TITLE
Erreur au lancement

### ISSUE THREAD

**Issue by anto1ne** [Rafbor42/RafCompta#1]
Erreur au lancement du logiciel.
Message d'erreur car il ne peux accéder à un fichier.

Pour reproduire le bug
* télécharger l'archive sur https://e-nautia.com/rafbor/disk?p=10432192
* chmod + x RafCompta
* ./RafCompta

![image](https://user-images.githubusercontent.com/44553182/212479025-6c63381d-88bb-40dc-8113-052425e8bfc5.png)

le logiciel ne semble pas fonctionnel par la suite.

**Comment by Rafbor42** [comment]
Hello, ce n'est pas un bug, je l'ai expliqué dans le fichier Readme au _§Principe de fonctionnement_, au 1er lancement il y a ce message car l'appli charge automatiquement les comptes existants. Il faut donc créer un compte après le 1er lancement.

**Comment by anto1ne** [comment]
ok, je n'avais pas fait attention
il serait peut être plus simple d'afficher l'interface pour ajouter un premier compte dans ce cas

**Comment by Rafbor42** [comment]
Bonne idée, je vais regarder ça. Merci.

**Comment by Rafbor42** [comment]
Mise à jour effectuée, v1.3.0116.0. Si le fichier contenant les comptes n'existe pas, on enchaîne sur la création d'un compte.
