### ISSUE TITLE
Erreur dans "A propos"

### ISSUE THREAD

**Issue by anto1ne** [Rafbor42/RafCompta#2]
(version venant de https://e-nautia.com/rafbor/disk?p=10432192 )

L'image est manquante et le bouton licence ne fonctionne pas

![image](https://user-images.githubusercontent.com/44553182/212479365-b077770e-feb6-404c-bf95-db5e9fba8945.png)

message d'erreur suivant

`(RafCompta:24752): Gtk-WARNING **: 16:16:32.378: Could not load image 'comptabilite.png': Impossible d’ouvrir le fichier « /home/antoine/Bureau/RafCompta_1.3.0113.1_avec_runtime/comptabilite.png » : Aucun fichier ou dossier de ce type
`

**Comment by Rafbor42** [comment]
J'aurai du mettre l'image _comptabilite.png_ dans l'archive, je l'ajouterai à la prochaine version.
Tu peux la récupérer dans le dossier _images_ et la copier dans le dossier du programme.

Pour le bouton _License_, j'avais vu le problème mais je ne m'en suis pas occupé, c'est une boite de dialogue générée automatiquement par Glade, il faut que je cherche comment câbler l'action du bouton.

**Comment by Rafbor42** [comment]
Mise à jour effectuée, v1.3.0116.0, le bouton _License_ n'est plus affiché et l'image est incluse dans l'archive.
