### ISSUE TITLE
Choix du compte

### ISSUE THREAD

**Issue by ventoux84** [Rafbor42/RafCompta#3]
A son ouverture, l'application demande de choisir un compte.

Quand il n'y en a qu'un, il pourrait être sélectionné par défaut. Un paramètre pourrait aussi désigner le compte par défaut quand il y en a plusieurs. Ou alors sélectionner par défaut le dernier utilisé.

**Comment by Rafbor42** [comment]
Bonne idée, je vais implémenter ça, merci.

**Comment by Rafbor42** [comment]
Mise à jour effectuée, v1.4.0130.0. A l'ouverture, le dernier compte utilisé est chargé.
