### ISSUE TITLE
Libellé de la zone pour choisir un compte.

### ISSUE THREAD

**Issue by ventoux84** [Rafbor42/RafCompta#4]
Quand on ouvre l'application, il y a une zone de choix en haut à droite pour sélectionner un compte. Son libellé est "Compte courant".
C'est un terme trop restrictif car l'application peut gérer n'importe quel type de compte qui fonctionne avec dépenses et recettes comme par exemple les livrets d'épargne et autres placements du même genre.

Donc "Compte" tout court serait plus adapté.

**Comment by Rafbor42** [comment]
C'est du à une mauvaise interprétation de ma part, je voulais désigner le compte actif dans l'application, et c'est vrai que cela porte à confusion. Je le modifierai ainsi que tous les messages qui y font référence.

**Comment by Rafbor42** [comment]
Mise à jour effectuée, v1.4.0130.0. Toutes les références au compte courant sont remplacées par compte actif.
